# Generated by Django 4.1.6 on 2023-03-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLevelCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Core/Static/Photos/FirstLevelCategories')),
            ],
        ),
        migrations.CreateModel(
            name='SecondLevelCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='Core/Static/Photos/SecondLevelCategories')),
                ('parent_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.firstlevelcategories')),
            ],
        ),
    ]
