# Generated by Django 4.1.7 on 2023-04-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_firstlevelcategories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstlevelcategories',
            name='name_el',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='firstlevelcategories',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='firstlevelcategories',
            name='short_name_el',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='firstlevelcategories',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='secondlevelcategories',
            name='name_el',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondlevelcategories',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondlevelcategories',
            name='short_name_el',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='secondlevelcategories',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
