# Generated by Django 4.1.7 on 2023-04-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_firstlevelcategories_name_el_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstlevelcategories',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='firstlevelcategories',
            name='short_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='firstlevelcategories',
            name='short_name_el',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='firstlevelcategories',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='firstlevelcategories',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategories',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategories',
            name='name_el',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategories',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategories',
            name='parent_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.firstlevelcategories', verbose_name='parent cat'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategories',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategories',
            name='short_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategories',
            name='short_name_el',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategories',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategories',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='slug'),
        ),
    ]
