# Generated by Django 4.1.7 on 2023-04-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_firstlevelcategories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstlevelcategories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Core/Static/Photos/FirstLevelCategories', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Core/Static/Photos/SecondLevelCategories', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategories',
            name='parent_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.firstlevelcategories', verbose_name='parent category'),
        ),
    ]
