# Generated by Django 4.1.7 on 2023-04-06 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, null=True)),
                ('phoneCode', models.CharField(max_length=4, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Industry_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformUsersAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('company_position', models.CharField(max_length=20, null=True)),
                ('phone_landline_number', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_mobile_number', models.CharField(blank=True, max_length=12, null=True)),
                ('street_address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('region', models.CharField(max_length=20, null=True)),
                ('zipcode', models.CharField(max_length=30, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.country')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.industry_type')),
                ('phone_landline_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landline_country', to='Accounts.country')),
                ('phone_mobile_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_country', to='Accounts.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform User',
                'verbose_name_plural': 'Platform Users',
            },
        ),
    ]
