# Generated by Django 4.1.7 on 2023-04-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry_type',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='company_name',
            field=models.CharField(max_length=50, null=True, verbose_name='company_name'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='company_position',
            field=models.CharField(max_length=20, null=True, verbose_name='company_position'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.industry_type', verbose_name='industry'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='region',
            field=models.CharField(max_length=20, null=True, verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='street_address',
            field=models.CharField(max_length=100, null=True, verbose_name='street_address'),
        ),
    ]
