# Generated by Django 4.1.7 on 2023-03-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_address_id_alter_country_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformusers',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
