# Generated by Django 4.1.7 on 2023-03-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_platformusers_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformusers',
            name='is_email_verified',
        ),
    ]
