# Generated by Django 4.1.7 on 2023-04-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_industry_type_name_alter_platformusersall_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformusersall',
            name='zipcode',
            field=models.CharField(max_length=30, null=True, verbose_name='zipcode'),
        ),
    ]
