# Generated by Django 4.1.7 on 2023-04-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_platformusersall_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformusersall',
            name='company_name',
            field=models.CharField(max_length=50, null=True, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='company_position',
            field=models.CharField(max_length=20, null=True, verbose_name='company position'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='street_address',
            field=models.CharField(max_length=100, null=True, verbose_name='street address'),
        ),
    ]
