# Generated by Django 4.1.7 on 2023-04-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_platformusersall_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=3, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='country',
            name='phoneCode',
            field=models.CharField(max_length=4, null=True, verbose_name='phone code'),
        ),
    ]
