# Generated by Django 4.1.7 on 2023-04-19 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0006_alter_country_code_alter_country_phonecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code_el',
            field=models.CharField(max_length=3, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='country',
            name='code_en',
            field=models.CharField(max_length=3, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_el',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='country',
            name='phoneCode_el',
            field=models.CharField(max_length=4, null=True, verbose_name='phone code'),
        ),
        migrations.AddField(
            model_name='country',
            name='phoneCode_en',
            field=models.CharField(max_length=4, null=True, verbose_name='phone code'),
        ),
        migrations.AddField(
            model_name='industry_type',
            name='name_el',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='industry_type',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='city_el',
            field=models.CharField(max_length=30, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='city_en',
            field=models.CharField(max_length=30, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='company_name_el',
            field=models.CharField(max_length=50, null=True, verbose_name='company name'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='company_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='company name'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='company_position_el',
            field=models.CharField(max_length=20, null=True, verbose_name='company position'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='company_position_en',
            field=models.CharField(max_length=20, null=True, verbose_name='company position'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='industry_el',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.industry_type', verbose_name='industry'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='industry_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.industry_type', verbose_name='industry'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='phone_landline_country_el',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landline_country', to='Accounts.country'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='phone_landline_country_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landline_country', to='Accounts.country'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='phone_landline_number_el',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='phone_landline_number_en',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='phone_mobile_country_el',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_country', to='Accounts.country'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='phone_mobile_country_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_country', to='Accounts.country'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='phone_mobile_number_el',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='phone_mobile_number_en',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='region_el',
            field=models.CharField(max_length=20, null=True, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='region_en',
            field=models.CharField(max_length=20, null=True, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='street_address_el',
            field=models.CharField(max_length=100, null=True, verbose_name='street address'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='street_address_en',
            field=models.CharField(max_length=100, null=True, verbose_name='street address'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='user_el',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='user_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='zipcode_el',
            field=models.CharField(max_length=30, null=True, verbose_name='zipcode'),
        ),
        migrations.AddField(
            model_name='platformusersall',
            name='zipcode_en',
            field=models.CharField(max_length=30, null=True, verbose_name='zipcode'),
        ),
    ]
