# Generated by Django 4.1.7 on 2023-04-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_country_code_el_country_code_en_country_name_el_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='industry_type',
            options={'verbose_name': 'Industry Type', 'verbose_name_plural': 'Industry Types'},
        ),
    ]
