# Generated by Django 4.1.7 on 2023-04-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_country_options_alter_industry_type_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformusersall',
            name='user_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='user_en',
        ),
    ]
