# Generated by Django 4.1.7 on 2023-04-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_remove_platformusersall_user_el_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code_el',
        ),
        migrations.RemoveField(
            model_name='country',
            name='code_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='phoneCode_el',
        ),
        migrations.RemoveField(
            model_name='country',
            name='phoneCode_en',
        ),
    ]
