# Generated by Django 4.1.7 on 2023-04-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_remove_country_code_el_remove_country_code_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformusersall',
            name='phone_landline_number_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='phone_landline_number_en',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='phone_mobile_number_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='phone_mobile_number_en',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='zipcode_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='zipcode_en',
        ),
    ]
