# Generated by Django 4.1.7 on 2023-04-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_remove_platformusersall_phone_landline_number_el_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformusersall',
            name='city_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='city_en',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='company_name_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='company_name_en',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='company_position_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='company_position_en',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='industry_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='industry_en',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='phone_landline_country_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='phone_landline_country_en',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='phone_mobile_country_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='phone_mobile_country_en',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='region_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='region_en',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='street_address_el',
        ),
        migrations.RemoveField(
            model_name='platformusersall',
            name='street_address_en',
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='phone_landline_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landline_country', to='Accounts.country', verbose_name='phone landline country'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='phone_landline_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='phone landline number'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='phone_mobile_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile_country', to='Accounts.country', verbose_name='phone mobile country'),
        ),
        migrations.AlterField(
            model_name='platformusersall',
            name='phone_mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='phone mobile number'),
        ),
    ]
