# Generated by Django 4.1.6 on 2023-04-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdisplayed',
            name='for_sell_rent',
            field=models.CharField(blank=True, choices=[('Renting', 'For Renting'), ('Selling or Renting', 'For Selling or Renting'), ('Selling', 'For Selling')], max_length=40, null=True, verbose_name='For sell, rent or both'),
        ),
        migrations.CreateModel(
            name='PalletizerSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('layer', 'Layer'), ('gantry', 'Gantry'), ('robotic', 'Robotic'), ('other', 'Other')], max_length=25, null=True, verbose_name='Palletizer Type')),
                ('throughput', models.FloatField(verbose_name='Throughput (pieces/min)')),
                ('application', models.CharField(blank=True, max_length=80, null=True, verbose_name='Application')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed')),
            ],
        ),
    ]
