# Generated by Django 4.1.6 on 2023-04-21 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_firstlevelcategories_icon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casepackerspecs',
            options={'verbose_name': 'Case Packer spec', 'verbose_name_plural': 'Case Packer specs'},
        ),
        migrations.AlterModelOptions(
            name='casesealerspecs',
            options={'verbose_name': 'Case Sealers Spec', 'verbose_name_plural': 'Case Sealers Specs'},
        ),
        migrations.AlterModelOptions(
            name='dispersersspecs',
            options={'verbose_name': 'Dispersers spec', 'verbose_name_plural': 'Dispersers specs'},
        ),
        migrations.AlterModelOptions(
            name='palletizerspecs',
            options={'verbose_name': 'Palletizer spec', 'verbose_name_plural': 'Palletizer specs'},
        ),
        migrations.AlterModelOptions(
            name='productphotos',
            options={'verbose_name': 'Product Photo', 'verbose_name_plural': 'Product Photos'},
        ),
        migrations.AlterModelOptions(
            name='thirdlevelcategories',
            options={'verbose_name': 'Third Level Category', 'verbose_name_plural': 'Third Level Categories'},
        ),
        migrations.AddField(
            model_name='casepackerspecs',
            name='type_el',
            field=models.CharField(blank=True, choices=[('top', 'Top Loader'), ('side', 'Side Loader'), ('P&PL', 'Pick and Place')], max_length=25, null=True, verbose_name='Case Packer Type'),
        ),
        migrations.AddField(
            model_name='casepackerspecs',
            name='type_en',
            field=models.CharField(blank=True, choices=[('top', 'Top Loader'), ('side', 'Side Loader'), ('P&PL', 'Pick and Place')], max_length=25, null=True, verbose_name='Case Packer Type'),
        ),
        migrations.AddField(
            model_name='casesealerspecs',
            name='type_el',
            field=models.CharField(blank=True, choices=[('BtmDr', 'Bottom Driven'), ('SdDr', 'Side Driven'), ('T&BtmDr', 'Top & Bottom Driven')], max_length=25, null=True, verbose_name='Case Sealer Type'),
        ),
        migrations.AddField(
            model_name='casesealerspecs',
            name='type_en',
            field=models.CharField(blank=True, choices=[('BtmDr', 'Bottom Driven'), ('SdDr', 'Side Driven'), ('T&BtmDr', 'Top & Bottom Driven')], max_length=25, null=True, verbose_name='Case Sealer Type'),
        ),
        migrations.AddField(
            model_name='dispersersspecs',
            name='application_el',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='dispersersspecs',
            name='application_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='dispersersspecs',
            name='type_el',
            field=models.CharField(blank=True, choices=[('batch', 'Batch'), ('continuous', 'Continuous')], max_length=25, null=True, verbose_name='Batch/Continuous'),
        ),
        migrations.AddField(
            model_name='dispersersspecs',
            name='type_en',
            field=models.CharField(blank=True, choices=[('batch', 'Batch'), ('continuous', 'Continuous')], max_length=25, null=True, verbose_name='Batch/Continuous'),
        ),
        migrations.AddField(
            model_name='palletizerspecs',
            name='application_el',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='palletizerspecs',
            name='application_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='palletizerspecs',
            name='type_el',
            field=models.CharField(blank=True, choices=[('layer', 'Layer'), ('gantry', 'Gantry'), ('robotic', 'Robotic'), ('other', 'Other')], max_length=25, null=True, verbose_name='Palletizer Type'),
        ),
        migrations.AddField(
            model_name='palletizerspecs',
            name='type_en',
            field=models.CharField(blank=True, choices=[('layer', 'Layer'), ('gantry', 'Gantry'), ('robotic', 'Robotic'), ('other', 'Other')], max_length=25, null=True, verbose_name='Palletizer Type'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='manufacturer_el',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='manufactured'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='manufacturer_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='manufactured'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='model_el',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='model_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='product_name_el',
            field=models.CharField(max_length=200, null=True, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='product_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='product_short_description_el',
            field=models.TextField(blank=True, null=True, verbose_name='product short description'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='product_short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='product short description'),
        ),
        migrations.AddField(
            model_name='thirdlevelcategories',
            name='name_el',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='thirdlevelcategories',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='thirdlevelcategories',
            name='short_name_el',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AddField(
            model_name='thirdlevelcategories',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='casepackerspecs',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='casesealerspecs',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='dispersersspecs',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='palletizerspecs',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='for_sell_rent',
            field=models.CharField(blank=True, choices=[('Renting', 'For Renting'), ('Selling', 'For Selling'), ('Selling or Renting', 'For Selling or Renting')], max_length=40, null=True, verbose_name='For sell, rent or both'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='manufactured_date',
            field=models.DateField(null=True, verbose_name='manufactured date'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='manufactured'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.thirdlevelcategories', verbose_name='product category'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='product_short_description',
            field=models.TextField(blank=True, null=True, verbose_name='product short description'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Core/Static/Photos/ThirdLevelCategories', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='parent_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.secondlevelcategories', verbose_name='parent category'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='short_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='slug'),
        ),
    ]
