# Generated by Django 4.1.7 on 2023-04-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_dispersersspecs_application_el_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casepackerspecs',
            name='type_el',
        ),
        migrations.RemoveField(
            model_name='casepackerspecs',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='casesealerspecs',
            name='type_el',
        ),
        migrations.RemoveField(
            model_name='casesealerspecs',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='dispersersspecs',
            name='type_el',
        ),
        migrations.RemoveField(
            model_name='dispersersspecs',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='palletizerspecs',
            name='type_el',
        ),
        migrations.RemoveField(
            model_name='palletizerspecs',
            name='type_en',
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='for_sell_rent',
            field=models.CharField(blank=True, choices=[('Selling or Renting', 'For Selling or Renting'), ('Renting', 'For Renting'), ('Selling', 'For Selling')], max_length=40, null=True, verbose_name='For sell, rent or both'),
        ),
    ]
