# Generated by Django 4.1.7 on 2023-04-20 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_alter_firstlevelcategories_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0029_alter_productsdisplayed_for_sell_rent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thirdlevelcategories',
            options={'verbose_name': 'Third Level Category', 'verbose_name_plural': 'Third Level Categories'},
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='product_category_el',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.thirdlevelcategories', verbose_name='product category'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='product_category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.thirdlevelcategories', verbose_name='product category'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='product_name_el',
            field=models.CharField(max_length=200, null=True, verbose_name='product name'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='product_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='casesealerspecs',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='productphotos',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='date_registered',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date registered'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='for_sell_rent',
            field=models.CharField(blank=True, choices=[('Selling', 'For Selling'), ('Selling or Renting', 'For Selling or Renting'), ('Renting', 'For Renting')], max_length=40, null=True, verbose_name='For sell, rent or both'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='manufactured_date',
            field=models.DateField(null=True, verbose_name='manufactered_date'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='manufactered'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.thirdlevelcategories', verbose_name='product category'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='product_short_description',
            field=models.TextField(blank=True, null=True, verbose_name='product short description'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='Core/Static/Photos/ThirdLevelCategories', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='name_el',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='parent_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.secondlevelcategories', verbose_name='parent cat'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='short_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='short_name_el',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='short_name_en',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True, verbose_name='slug'),
        ),
    ]
