# Generated by Django 4.1.7 on 2023-04-20 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0030_alter_thirdlevelcategories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casepackerspecs',
            options={'verbose_name': 'Case Packer spec', 'verbose_name_plural': 'Case Packer specs'},
        ),
        migrations.AlterModelOptions(
            name='casesealerspecs',
            options={'verbose_name': 'Case Sealers Spec', 'verbose_name_plural': 'Case Sealers Specs'},
        ),
        migrations.AlterModelOptions(
            name='dispersersspecs',
            options={'verbose_name': 'Disperesers spec', 'verbose_name_plural': 'Dispereser specs'},
        ),
        migrations.AlterModelOptions(
            name='palletizerspecs',
            options={'verbose_name': 'Palletizer spec', 'verbose_name_plural': 'Palletizer specs'},
        ),
        migrations.AlterModelOptions(
            name='productphotos',
            options={'verbose_name': 'Product Photo', 'verbose_name_plural': 'Products Photos'},
        ),
        migrations.AddField(
            model_name='productphotos',
            name='product_el',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productphotos',
            name='product_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='casepackerspecs',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='dispersersspecs',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='palletizerspecs',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='for_sell_rent',
            field=models.CharField(blank=True, choices=[('Renting', 'For Renting'), ('Selling', 'For Selling'), ('Selling or Renting', 'For Selling or Renting')], max_length=40, null=True, verbose_name='For sell, rent or both'),
        ),
    ]
