# Generated by Django 4.1.7 on 2023-04-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0031_alter_casepackerspecs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphotos',
            name='photo_el',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='productphotos',
            name='photo_en',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='photo'),
        ),
    ]
