# Generated by Django 4.1.7 on 2023-04-28 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0032_contact_alter_productsdisplayed_for_sell_rent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='No name', max_length=200, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productsdisplayed', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='contact',
            name='reason',
            field=models.CharField(blank=True, choices=[('Reason1', 'Reason1'), ('Reason2', 'Reason2'), ('Reason3', 'Reason3')], max_length=40, null=True, verbose_name='Reason for your inquiry'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='for_sell_rent',
            field=models.CharField(blank=True, choices=[('Selling or Renting', 'For Selling or Renting'), ('Renting', 'For Renting'), ('Selling', 'For Selling')], max_length=40, null=True, verbose_name='For sell, rent or both'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='for_sell_rent_el',
            field=models.CharField(blank=True, choices=[('Selling or Renting', 'For Selling or Renting'), ('Renting', 'For Renting'), ('Selling', 'For Selling')], max_length=40, null=True, verbose_name='For sell, rent or both'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='for_sell_rent_en',
            field=models.CharField(blank=True, choices=[('Selling or Renting', 'For Selling or Renting'), ('Renting', 'For Renting'), ('Selling', 'For Selling')], max_length=40, null=True, verbose_name='For sell, rent or both'),
        ),
    ]
