# Generated by Django 4.1.7 on 2023-04-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0032_productphotos_photo_el_productphotos_photo_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdisplayed',
            name='for_sell_rent',
            field=models.CharField(blank=True, choices=[('Selling', 'For Selling'), ('Selling or Renting', 'For Selling or Renting'), ('Renting', 'For Renting')], max_length=40, null=True, verbose_name='For sell, rent or both'),
        ),
    ]
