# Generated by Django 4.1.7 on 2023-04-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_alter_firstlevelcategories_icon_and_more'),
        ('Products', '0033_alter_productsdisplayed_for_sell_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdlevelcategories',
            name='parent_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.secondlevelcategories', verbose_name='parent category'),
        ),
    ]
