# Generated by Django 4.1.7 on 2023-04-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0034_alter_thirdlevelcategories_parent_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphotos',
            name='photo_el',
        ),
        migrations.RemoveField(
            model_name='productphotos',
            name='photo_en',
        ),
        migrations.RemoveField(
            model_name='productphotos',
            name='product_el',
        ),
        migrations.RemoveField(
            model_name='productphotos',
            name='product_en',
        ),
        migrations.RemoveField(
            model_name='productsdisplayed',
            name='product_category_el',
        ),
        migrations.RemoveField(
            model_name='productsdisplayed',
            name='product_category_en',
        ),
        migrations.AddField(
            model_name='casepackerspecs',
            name='type_el',
            field=models.CharField(blank=True, choices=[('top', 'Top Loader'), ('side', 'Side Loader'), ('P&PL', 'Pick and Place')], max_length=25, null=True, verbose_name='Case Packer Type'),
        ),
        migrations.AddField(
            model_name='casepackerspecs',
            name='type_en',
            field=models.CharField(blank=True, choices=[('top', 'Top Loader'), ('side', 'Side Loader'), ('P&PL', 'Pick and Place')], max_length=25, null=True, verbose_name='Case Packer Type'),
        ),
        migrations.AddField(
            model_name='casesealerspecs',
            name='type_el',
            field=models.CharField(blank=True, choices=[('BtmDr', 'Bottom Driven'), ('SdDr', 'Side Driven'), ('T&BtmDr', 'Top & Bottom Driven')], max_length=25, null=True, verbose_name='Case Sealer Type'),
        ),
        migrations.AddField(
            model_name='casesealerspecs',
            name='type_en',
            field=models.CharField(blank=True, choices=[('BtmDr', 'Bottom Driven'), ('SdDr', 'Side Driven'), ('T&BtmDr', 'Top & Bottom Driven')], max_length=25, null=True, verbose_name='Case Sealer Type'),
        ),
        migrations.AddField(
            model_name='dispersersspecs',
            name='application_el',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='dispersersspecs',
            name='application_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='dispersersspecs',
            name='type_el',
            field=models.CharField(blank=True, choices=[('batch', 'Batch'), ('continuous', 'Continuous')], max_length=25, null=True, verbose_name='Batch/Continuous'),
        ),
        migrations.AddField(
            model_name='dispersersspecs',
            name='type_en',
            field=models.CharField(blank=True, choices=[('batch', 'Batch'), ('continuous', 'Continuous')], max_length=25, null=True, verbose_name='Batch/Continuous'),
        ),
        migrations.AddField(
            model_name='palletizerspecs',
            name='application_el',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='palletizerspecs',
            name='application_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='palletizerspecs',
            name='type_el',
            field=models.CharField(blank=True, choices=[('layer', 'Layer'), ('gantry', 'Gantry'), ('robotic', 'Robotic'), ('other', 'Other')], max_length=25, null=True, verbose_name='Palletizer Type'),
        ),
        migrations.AddField(
            model_name='palletizerspecs',
            name='type_en',
            field=models.CharField(blank=True, choices=[('layer', 'Layer'), ('gantry', 'Gantry'), ('robotic', 'Robotic'), ('other', 'Other')], max_length=25, null=True, verbose_name='Palletizer Type'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='manufacturer_el',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='manufactered'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='manufacturer_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='manufactered'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='model_el',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='model_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='model'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='product_short_description_el',
            field=models.TextField(blank=True, null=True, verbose_name='product short description'),
        ),
        migrations.AddField(
            model_name='productsdisplayed',
            name='product_short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='product short description'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='for_sell_rent',
            field=models.CharField(blank=True, choices=[('Selling or Renting', 'For Selling or Renting'), ('Renting', 'For Renting'), ('Selling', 'For Selling')], max_length=40, null=True, verbose_name='For sell, rent or both'),
        ),
    ]
