# Generated by Django 4.1.7 on 2023-04-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0035_remove_productphotos_photo_el_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispersersspecs',
            options={'verbose_name': 'Dispersers spec', 'verbose_name_plural': 'Dispersers specs'},
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='manufactured_date',
            field=models.DateField(null=True, verbose_name='manufactured date'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='manufactured'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='manufacturer_el',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='manufactured'),
        ),
        migrations.AlterField(
            model_name='productsdisplayed',
            name='manufacturer_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='manufactured'),
        ),
    ]
