# Generated by Django 4.1.7 on 2023-04-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0036_alter_dispersersspecs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphotos',
            options={'verbose_name': 'Product Photo', 'verbose_name_plural': 'Product Photos'},
        ),
    ]
