# Generated by Django 4.1.7 on 2023-04-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0038_alter_contact_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='reason',
            field=models.CharField(blank=True, choices=[('Reason2', 'Reason2'), ('Reason1', 'Reason1'), ('Reason3', 'Reason3')], max_length=40, null=True, verbose_name='Reason for your inquiry'),
        ),
    ]
